(define (convert-negitive filename)
  (let* (
       (image (car (gimp-file-load RUN-NONINTERACTIVE filename filename)))
       (drawable (car (gimp-image-get-active-layer image)))
     )
     (gimp-image-crop image 1900 1350 1550 1000)
     (gimp-invert drawable)
     (gimp-equalize drawable FALSE)
     (set! drawable (car (gimp-image-get-active-layer image)))
     ;(gimp-file-save RUN-NONINTERACTIVE image drawable filename filename)
     (file-tiff-save RUN-NONINTERACTIVE image drawable filename filename 3)
     (gimp-image-delete image)
  )
)